### ISSUE TITLE
cannot build esm-bundle vaadin-dropdown-menu with polymer 3

### ISSUE THREAD

**Issue by jimmont** [vaadin/vaadin-dropdown-menu#123]
I can't seem to get polymer build to work due to a problem with the following imports related to vaadin-dropdown-menu,
the problem isn't clear to me. in looking at the file `@vaadin/vaadin-dropdown-menu/theme/lumo/vaadin-dropdown-menu-styles.js` mentioned in the error the import for lumo theme file `import '@vaadin/vaadin-item/theme/lumo/vaadin-item.js';` isn't clear as to why it could be a problem:

`polymer --version 1.7.1,
vaadin-dropdown-menu "version": "1.0.0-pre.3"
`
in my module I import with `import '@vaadin/vaadin-dropdown-menu/vaadin-dropdown-menu.js';` removing this import and the solution builds, otherwise I see the following error.

```
npm run build:static

> something@0.0.0 build:static /path/something
> polymer build

info: [cli.command.build]    Clearing build/ directory...
(node:34972) ExperimentalWarning: The fs.promises API is experimental
error: [cli.main]   Promise rejection: Error: Could not load file:///path/something/node_modules/%40vaadin/vaadin-dropdown-menu/theme/lumo/%40vaadin/vaadin-item/theme/lumo/vaadin-item.js (imported by file:///path/something/node_modules/%40vaadin/vaadin-dropdown-menu/theme/lumo/vaadin-dropdown-menu-styles.js): ENOENT: no such file or directory, open 'file:///path/something/node_modules/%40vaadin/vaadin-dropdown-menu/theme/lumo/%40vaadin/vaadin-item/theme/lumo/vaadin-item.js'
error: [cli.main]   Error: Could not load file:///path/something/node_modules/%40vaadin/vaadin-dropdown-menu/theme/lumo/%40vaadin/vaadin-item/theme/lumo/vaadin-item.js (imported by file:///path/something/node_modules/%40vaadin/vaadin-dropdown-menu/theme/lumo/vaadin-dropdown-menu-styles.js): ENOENT: no such file or directory, open 'file:///path/something/node_modules/%40vaadin/vaadin-dropdown-menu/theme/lumo/%40vaadin/vaadin-item/theme/lumo/vaadin-item.js'
    at /path/something/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:20561:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! something@0.0.0 build:static: `polymer build`
npm ERR! Exit status 1


```

**Comment by web-padawan** [comment]
Which node version are you using? I'm unable to reproduce this issue.

Please try to use our Polymer 3 starter application. In order to do this, you need following steps:

1. Clone the template and link it:
```sh
git clone --depth 1 -b p3-preview git://github.com/vaadin/generator-polymer-init-vaadin-elements-app.git && cd generator-polymer-init-vaadin-elements-app && npm link
```
2. Create a new empty folder:
```sh
mkdir p3-test && cd test
```
3. Run the generator:
```sh
polymer init vaadin-elements-app
```
4. Build the project
```sh
polymer build
```
5. Serve the build output:
```sh
polymer serve build/default --npm
```

I have tried these steps using LTS node 8.11.1 and have not seen any errors, neither the warning you have `(node:34972) ExperimentalWarning: The fs.promises API is experimental`. As of now, Polymer tools do not work properly with node 10, so if you have that version, you should downgrade.

**Comment by jimmont** [comment]
thanks @web-padawan, I was using node 10.1.0 (and polymer-cli 1.7.1)--updated to it yesterday. These inter-dependencies got me.
