### ISSUE TITLE
`label` attribute for custom values is confusing

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-dropdown-menu#13]
It is confusing that we use `label` in items for setting the selected value.
`label` is used in most of our elements for a different purpose.
```
<vaadin-dropdown-menu label="Select a Name">
   <template>
      <vaadin-list-box >
         <vaadin-item label='Manuel'>Manolo</vaadin-item>
```

I suggest to use `value` which is used in native select/option tags

```
<select>
  <option value="volvo">Volvo</option>
```

**Comment by jouni** [comment]
Well, I don’t think it’s confusing, as the attribute is placed on the item. It provides the same feature – the visual and audible label for that particular focusable piece of UI. 

“Value” sounds more like the underlying data that gets submitted in a form (or used in a data binding), like an `id`. That would be more confusing IMO.

**Comment by manolo** [comment]
Sorry, already working on this and sent a fix, before reading this.
If you don't consider this confusing let's go with label, but as I said we should align with the platform as much as possible. Since we are in very early alpha status, changing the API here shouldn't be a big deal

**Comment by jouni** [comment]
> we should align with the platform as much as possible

If you refer to the `value` attribute for `option` elements than that is another thing. It does not change the visual label of the item/option, only the value which is used in form submission.

If you mean something else, can you please clarify?

**Comment by jouni** [comment]
So IMO, please revert back to using `label` instead.

This does not rule out the possibility of introducing another `value` property/attribute in addition, which would then match with the `vaadin-combo-box` API.

**Comment by manolo** [comment]
Out of curiosity why is in vaadin-radio-button the same thing named `value` shouldn't we be aligned in the api we offer in all elements?

**Comment by jouni** [comment]
In `vaadin-radio-button`, the `value` property/attribute is also used for form submission, not for the visible/audible label for the control.

For example:
```html
<vaadin-radio-button value="item_1234">Item name (id: 1234)</vaadin-radio-button>
```

The end user would see `⦿ Item name (id: 1234)` and a screen reader would announce something like `Item name, id 1234, radio button, checked`.
