### ISSUE TITLE
Sets value to empty when deleted

### ISSUE THREAD

**Issue by tomalec** [vaadin/vaadin-dropdown-menu#130]
### Description
The element sets the bound value to empty when it's deleted. Which is extremely undesired, when the dropdown is used to set a value, then dismissed as a modal or page navigated away in SPA.

Not to mention cases when the data is bound to a proxy, that instantly reacts to the changes with triggering actions on the server.
 
#### Live Demo
https://jsbin.com/zigijed/edit?html,output
 
#### Steps to Reproduce
1. Create and append `vaadin-dropdown-menu` bound to a value
2. Pick a value,
3. Remove `vaadin-dropdown-menu`

```html
<dom-bind id="db">
  <template>
    Please pick a value from `vaadin-dropdown-menu`, then click on the button, observing how the value changes.
    <p>Picked value: <span>{{model.selectedItem}}</span></p>
    <vaadin-dropdown-menu id="dd" label="Label" placeholder="Placeholder" value="{{model.selectedItem}}" on-value-changed="{{remove}}">
      <template>
        <vaadin-list-box>
          <template is="dom-repeat" items="{{model.items}}">
            <vaadin-item value="{{item}}">{{item}}</vaadin-item>
          </template>
          <hr>
          <vaadin-item disabled>Option four</vaadin-item>
        </vaadin-list-box>
      </template>
    </vaadin-dropdown-menu>
    <button id="closeBtn">Click to close once done with selection</button>
  </template>
</dom-bind>
<script>
  db.set('model', {items: ["one", "two"], selectedItem: "one"})
  closeBtn.addEventListener('click', ()=>{
    dd && dd.remove();
  });
</script>
```
 
#### Expected Results
The value should remain as it was picked.
 
#### Actual Results
Value is always set to empty string`""`.
 
### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 9
- [?] Safari 8
- [x] IE 11
 
### Versions
- vaadin-dropdown-menu: https://github.com/vaadin/vaadin-dropdown-menu/tree/62eca8957aea266514b180564d87e7285874bf84 (master)
- webcomponents: https://github.com/webcomponents/webcomponentsjs/tree/a957286fa3cb157695cb82a1cdd9c822290f73d6(v1)

**Comment by platosha** [comment]
This seems to be a bad side-effect of the `Vaadin.ListMixin`’s observer for items and the way the value matching works in the `<vaadin-dropdown-menu>`.
- During the removal, the items are removed before the dropdown menu, and removal of every item triggers the items observer. This notifies the dropdown-menu of the items array change.
- Then, the `<vaadin-dropdown-menu>` tries to update the selected item based on the “new” items list.
- At some point the item corresponding to the value gets removed. As the `<vaadin-dropdown-menu>` in that case cannot find the selected item, it sets the value to `''`.

I don’t have a good quick fix idea for that. The `<vaadin-dropdown-menu>` value matching behaviour seems to mimic the one of the native `<select>`, which also changes the value if an item is removed, as I can see. But this is, of course, unexpected that the value change notification of any sort happens on removal (the native `<select>` does not notify the value change on removal too).

Maybe `<vaadin-dropdown-menu>` should detect its removal level before the items start to disappear, and disable the items change reaction. Hope, `disconnectedCallback()` can do that before it calls `super.disconnectedCallback()`, but not sure.
