### ISSUE TITLE
The first time an invalid value is set, it remains instead of be reset to empty

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-dropdown-menu#136]
In first demo try to set `$0.value = 'foo' ; $0.value`  it prints `foo`  otherwise if you do `$0.value = 'Manolo'; $0.value = 'foo'; $0.value` it modifies the incorrect value to an empty `""` string

**Comment by web-padawan** [comment]
Fixed in #137 and cherry-picked to "vaadin-10" branch in 21603e7
