### ISSUE TITLE
Move overlay wiring out from the ready block

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-dropdown-menu#138]
All the code in this block is ignored if `this._overlayElement.content` doesn't happen to exist when `ready()` is invoked: https://github.com/vaadin/vaadin-dropdown-menu/blob/master/src/vaadin-dropdown-menu.html#L340

And since `ready()` is invoked only once, the component can remain broken for the rest of its lifespan.

Add a MutationObserver to the component instead and do the wiring only once a template or a renderer is received.

**Comment by web-padawan** [comment]
Note: also breaks the renderer function when using in lit-element
https://glitch.com/edit/#!/zesty-bumper?path=app.js:35:11
