### ISSUE TITLE
Material Theme

### ISSUE THREAD

**Issue by JMurph2015** [vaadin/vaadin-dropdown-menu#144]
Hi!
I tried using the process from the theming [documentation](https://cdn.vaadin.com/vaadin-material-theme/0.4.0/demo/) but it doesn't seem to have taken effect when I used a vaadin-dropdown-menu.  Is there something I'm missing or a workaround?
Thanks!

**Comment by jouni** [comment]
Hi! 

If you are using the latest pre-release version, you should import `vaadin-dropdown-menu/theme/material/vaadin-dropdown-menu.html` instead of `vaadin-dropdown-menu/vaadin-dropdown-menu.html` (which is the default Lumo theme).

**Comment by web-padawan** [comment]
Updated Material theme documentation to [1.1.0-beta1](https://cdn.vaadin.com/vaadin-material-styles/1.1.0-beta1/demo/) and the description of [entry points](https://github.com/vaadin/vaadin-dropdown-menu#entry-points) in README. Please follow these links if you still experience problems. 

Closing as this is a question, not an issue in the component. Questions should be asked at https://gitter.im/vaadin/web-components or https://polymer.slack.com/messages/C6ULJ2F7S
