### ISSUE TITLE
When setting the value, item in the overlay should be selected

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-dropdown-menu#15]
It needs some changes in `vaadin-list-box` see  https://github.com/vaadin/vaadin-list-box/issues/7

**Comment by tomivirkki** [comment]
Shouldn't `value` be read-only? Example: https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu/elements/paper-dropdown-menu#property-value

**Comment by manolo** [comment]
As far as I know, this component should replace vaadin-combo-box in bakery, so it should be possible to set the value with the item in the database.
Also this element should be a replacement for the native select that allows to execute `select.value = 'foo'`
Not familiar with paper solution though

**Comment by tomivirkki** [comment]
The value of `<vaadin-dropdown-menu>` is by default `textContent` of a listed item. It would be weird if you had to set the value to match `textContent` of some arbitrary html content (that might not event have been stamped yet). Only logical API for selecting would be to mark an item as `selected`. @jouni?

**Comment by jouni** [comment]
Well, I see this working the same way as combo box and radio group: each item can have a specified “value” to which we can match.

For example:

```html
<vaadin-dropdown-menu selected="1234">
  <template>
    <vaadin-list-box>
      <vaadin-item value="1234">Jose</vaadin-item>
      <vaadin-item value="2345">Manolo</vaadin-item>
      <vaadin-item value="3456">Pedro</vaadin-item>
    </vaadin-list-box>
  </template>
</vaadin-dropdown-menu>
```

Without that, you are right, it doesn’t make much sense to match to the `textContent`. Although, for simple string content that could be very convenient. But I’m not sure that use case is that relevant.

### Bonus question:

Can we omit the `<vaadin-list-box>` from the boilerplate, and just have:

```html
<vaadin-dropdown-menu selected="1234">
  <template>
    <vaadin-item value="1234">Jose</vaadin-item>
    <vaadin-item value="2345">Manolo</vaadin-item>
    <vaadin-item value="3456">Pedro</vaadin-item>
  </template>
</vaadin-dropdown-menu>
```

It’s not like you should be putting anything else there, right?

**Comment by manolo** [comment]
@jouni you meant `value` or `label` as the custom value we are copying to the dropdown value ? 

Related with textContent, I agree that is convenient to select it, in this way is done with native select

```
<select>
  <option value="volvo">Volvo</option>
  <option >Audi</option>
</select>

select.value = 'volvo' -> selects 1st item
select.value = 'Volvo' -> selects empty
select.value = 'Audi' -> selects 2nd item
```

**Comment by platosha** [comment]
Side note: not having a `value` property on `<vaadin-dropdown-menu>` makes it harder to submit it in `<iron-form>`. Would prefer having `value` both on items and on the menu element.

What concerns the bonus question: let us consider shortcuts later. Would prefer explicit `<vaadin-list-box>`.

**Comment by manolo** [comment]
Not having `<vaadin-list-box>` needs to include the nav complexity into the dropdown.
It also might remove the current feature of replacing vaadin-list-box with vaadin-tabs or any other custom element the developer could make.

**Comment by platosha** [comment]
Having explicit `<vaadin-list-box>` allows more flexible use in the future: user’s custom list box elements inside, arbitrary dropdown content aside the list box, and so on.

It does not mean we have to support all of these use cases in the first version. For now, we can document that only `<vaadin-list-box>` is supported. What I like about explicit `<vaadin-list-box>` is that this kind of an API is more open for adding dropdown content customisation features in future. Shortcuts could be added later as well.

**Comment by jouni** [comment]
> What concerns the bonus question: let us consider shortcuts later.

Yes, absolutely. I just couldn’t help myself and wanted to ask this already.

> Not having <vaadin-list-box> needs to include the nav complexity into the dropdown.

My thinking was that we could “inject” that automatically in the shadow DOM. So in the end `vaadin-list-box` would still be there handling the navigation, but we would make the dropdown-menu API a bit more convenient.

> this kind of an API is more open for adding dropdown content customisation features in future

Yeah, it has more flexibility, which I would not like to lose either. Just thinking if we would want to make some conditional magic depending on what element is used as the direct child of the template.

**Comment by jouni** [comment]
> @jouni you meant value or label ? as the custom label is what we are copying to the dropdown value ?

I meant `value`, not the visible label in the UI.

**Comment by manolo** [comment]
> My thinking was that we could “inject” that automatically in the shadow DOM

**Comment by manolo** [comment]
> My thinking was that we could “inject” that automatically in the shadow DOM

I see the point, yes that is doable

**Comment by manolo** [comment]
So my proposal for setting the value is:

When `dropdown.value` changes, it visits the array `dropdown._menuElement._navItems` (`_menuElement` is a `Vaadin.ListMixin`), and calculates the selected index based on the first element that matches the `value` attribute, the `label` attribute or the `textContent` string, and updates the `selected` property of the `_menuElement` appropriately.

**Comment by tomivirkki** [comment]
Maybe we could limit it to `value`. "..the label attribute or the textContent string" could make it quite magical

**Comment by tomivirkki** [comment]
Also, this would not block us from later adding a property like `attr-for-value` (that would default to `value`)

**Comment by manolo** [comment]
> Maybe we could limit it to value

**Comment by manolo** [comment]
> Maybe we could limit it to value

Which implies that the users always need to provide a value. I feel like we have to remove the code that assigns `dropdown.value = label || textContent`

**Comment by tomivirkki** [comment]
Had a discussion with the team and PM and the following was agreed:

- `<vaadin-dropdown-menu>` should have a read/write `value` property.
- The `value` property will change only if a `<vaadin-item>` with `value` defined gets selected. In that case, `value` will equal to that of the `<vaadin-item>`’s.
- If `<vaadin-dropdown-menu>`’s `value`is changed, a `<vaadin-item>` with a matching `value` gets selected (if one exists).
- Align behaviour with `<vaadin-radio-group>`

`value` is optional for the `<vaadin-item>`s since `<vaadin-dropdown-menu>` can still be used without `value` for example by binding to `selected` property of the wrapped `<vaadin-list-box>` or `selected` property of `<vaadin-item>`s.

**Comment by jouni** [comment]
Now I’m wondering about the semantic difference between “value” and “selected”…

**Comment by manolo** [comment]
well selected will be needed when multi-select menus
