### ISSUE TITLE
Fix the regression from #162

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-dropdown-menu#163]
Try the first demo: the list gets new items every time it's opened

![screenshot 2018-09-05 09 33 39](https://user-images.githubusercontent.com/1222264/45075150-d5c59180-b0ee-11e8-9e8b-fe21d5703827.png)

**Comment by tomivirkki** [comment]
Most likely it's just an issue with the demo.

**Comment by web-padawan** [comment]
Should be fixed in #157 along with other fixes.

**Comment by tomivirkki** [comment]
#157 still seems to have this (demo) issue
