### ISSUE TITLE
Broken touch device behavior

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-dropdown-menu#23]
Since there’s a readonly input which gets focused on tap, the viewport zooms in on that input making the overlay be misaligned. They input also shows that the value has a lot of extra white space characters after the actual value.

![vaadin-dropdown-menu-iphone](https://user-images.githubusercontent.com/66382/32265097-38358c64-beea-11e7-8186-8d64b255c986.gif)

**Comment by manolo** [comment]
> the viewport zooms in on that input

**Comment by manolo** [comment]
> the viewport zooms in on that input

**Comment by manolo** [comment]
> the viewport zooms in on that input 

@jouni  I apparently fixed the problem in focus, so now there is no zoom, but still the viewport used by the overlay is not the device dimensions but the body. Can you verify?

**Comment by jouni** [comment]
It still zooms. Also, I’m still able to focus the input field on the first time. 

And the focus state stays even after I select an option from the list. The field should be blurred when the overlay closes (on touch devices).

![vaadin-dropdown-menu-iphone2](https://user-images.githubusercontent.com/66382/32280286-ffc60270-bf23-11e7-83ac-2bd9ea958e4c.gif)

**Comment by manolo** [comment]
I see. I thought it was not zooming with my approach but was because I didn't zoom back. This PR is not the best approach.

**Comment by manolo** [comment]
Updated the PR with the fix, I tested in simulator. @jouni  let me know if it works for you, thanks

**Comment by jouni** [comment]
Yeah, now it looks like it works properly, at least on iOS11.
