### ISSUE TITLE
UX/DX tests and fixes

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-dropdown-menu#3]
Plan, book, conduct and report.

**Comment by YuriyVaadin** [comment]
<b>UX Part</b> will be conducted with demo pages of the `vaadin-dropdown-menu`
<b>DX Part</b> https://gitlab.vaadin.com/elements/dx-tests/compare/master...wip%2Fvaadin-dropdown-menu%2Fv1.0.0-alpha1

**Comment by YuriyVaadin** [comment]
<b>Prepared combined document:</b> https://docs.google.com/document/d/1TnoPew1xZwwsvX9GwGelX98IByZ69J1ysLi9eVn6t4I/edit#heading=h.u1kv5zpv1526
