### ISSUE TITLE
Right arrow used for opening of the dropdown?

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-dropdown-menu#41]
One of the participants has proposed to include <kbd>&rarr;</kbd> (right arrow) to the list of the keyboard keys that are opening the dropdown-menu.

**Comment by jouni** [comment]
I see no strong reason to add this unless ARIA best practices include it.

**Comment by web-padawan** [comment]
From my previous experience, arrow keys might be useful for horizontal scroll, if there is one (which is generally a bad practice but in some cases it is difficult to use better solution).

**Comment by jouni** [comment]
I say we close this, as it’s not a strict requirement. Feel free to comment if you disagree.
