### ISSUE TITLE
It should be possible to add an toggle button/icon with a theme

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-dropdown-menu#51]
A drop-down menu is commonly recognized by an arrow button at the end of the field.

It is possible to add it using a pseudo-element, but it’s really tricky and in some themes, the appropriate pseudo-elements are already in use for other purposes.

**Comment by tomivirkki** [comment]
Should we have it there by default (like combo-box does?)

**Comment by jouni** [comment]
I think yes.
