### ISSUE TITLE
Remove native text input from `vaadin-dropdown-menu-text-field`

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-dropdown-menu#56]
The element is currently hidden using `visiblity: hidden;`. That causes problems with the text-field default styles which apply flex for that part, making it take space in the layout even though invisible, and not allowing the `slot=selected` to take all of the available space.

How I see it, we should just remove the native `<input part="value">` from the `vaadin-dropdown-menu-text-field` template (or hide it explicitly with `display: none;`), and apply the “value” part for the selected slot instead: `<div slot="selected" part="value"></div>`.

**Comment by tomivirkki** [comment]
The `placeholder` currently uses the native input. Should we drop `placeholder`?

**Comment by jouni** [comment]
Hmm, didn’t realize that.

But when is the placeholder even shown? It seems the field will always have a value (unless we change it based on the discussion in #57).

Implementation details aside, a placeholder is a nice feature to have. Not sure if the same thing could be supported with a special `<vaadin-item>` that marks a placeholder item.

**Comment by jouni** [comment]
I guess the least we should do is to completely hide the input (so that it doesn’t take space) when some item is selected and shown in the field.

After that, I think we should add `part="value"` to the selected element as well, so it automatically gets the same styles automatically.

Right now, I have to do both manually in Valo (hide the native input and copy-paste some padding values from text-field to dropdown).
