### ISSUE TITLE
Fix the default value of <vaadin-item> to be explicit value or textContent

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-dropdown-menu#57]
The current default `value` for each item is an empty string. This basically forces the developer to always specify the `value` attribute for all items.

It would be convenient if the default value of an item would be its index in the list.

**Comment by jouni** [comment]
This should probably be in `vaadin-list-box` repo instead. Feel free to move there if needed.

**Comment by jouni** [comment]
Another side-effect of having an empty string as the default value: when you make the dropdown menu `required` it’s always marked as invalid because the value if an empty string.

**Comment by jouni** [comment]
If we want to be aligned with the native select, the default value for each item should be the text content. That way it would be still easy to provide an initial empty value for the list.

Another option is to not always require the list-box to have a selected item by default (i.e. don’t automatically select the first item), unless explicitly selected in code.

**Comment by tomivirkki** [comment]
> It would be convenient if the default value of an item would be its index in the list.

If we switch to indexes, we should probably rename the property to `selected` to align with `<vaadin-list-box>`.

> If we want to be aligned with the native select, the default value for each item should be the text content. That way it would be still easy to provide an initial empty value for the list.

Native select can't have arbitrary HTML inside the options. It's always a plain string so it makes sense to use it as the default value. `<vaadin-item>` allows any HTML inside so using the text content as value would be strange. To select a certain option, you'd have to know what kind of text content it produces etc.

How about if
1. we aligned with `<paper-dropdown-menu>` and remove the default `value` from `<vaadin-dropdown-menu>`. Then no item would get selected by default as the property is undefined.
2. we drop the `value` property completely (for now at least). The internal `<vaadin-list-box>` already has `selected` which can be used instead.

**Comment by jouni** [comment]
So we don’t have a `selected` property yet? I suppose I was looking for that instead – something easy to bind to if I want to control some other part of the UI with a dropdown menu.

If we drop `value`, then `required` and `invalid` make no sense either. This is pretty much the same situation we went through with `vaadin-radio-group`. These elements (radio group, list box and dropdown menu) are pretty identical in API, in my opinion – they allow the user to choose exactly one option from a list, and the selection can be empty by default.

A list box can allow multiple selections, but that’s a different discussion in https://github.com/vaadin/vaadin-list-box/issues/10. That and `vaadin-checkbox-group` would be similar in API.

No concrete proposal here yet, just more food for thought.

**Comment by tomivirkki** [comment]
Decided to go with the approach: "Remove the default value from <vaadin-dropdown-menu>. Then no item would get selected by default as the property is undefined."

**Comment by tomivirkki** [comment]
After further discussion, we decided to change the default `value` of `<vaadin-item>` to be the textContent if explicit `value` isn't defined.
