### ISSUE TITLE
It should be possible to specify the error message

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-dropdown-menu#59]
Since the dropdown menu can be marked as required, it would be useful in some use cases to specify the error message shown to the end user (e.g. “Please choose one option”).

**Comment by vicsstar** [comment]
Is there a demo/sample of how you'd expect this error message to be displayed or, is it something you can describe in words here?

**Comment by web-padawan** [comment]
@vicsstar The internal text field already has the `errorMessage` property and corresponding shadow part.
See also the [validation](https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha4/demo/text-fields.html#validation) demo.
