### ISSUE TITLE
Keep overlay attached to the field when scrolling

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-dropdown-menu#6]
Currently, the overlay separates from the field when the browser viewport is scrolled.

**Comment by YuriyVaadin** [comment]
Fixed by https://github.com/vaadin/vaadin-dropdown-menu/commit/ed51e27e11e6aa4a8f8f49360af0f90d77fb59cd

**Comment by jouni** [comment]
Was there no review for this change?

**Comment by manolo** [comment]
This commit was part of PR https://github.com/vaadin/vaadin-dropdown-menu/pull/4
