### ISSUE TITLE
Regression: it is possible to edit internal text field

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-dropdown-menu#62]
Caused by #55

## Steps to reproduce:

1. open demo
2. press `Tab` to enter the demo with the placeholder
3. press `Tab` once again

The possible fix is to set `tabindex` to -1 on the underlying native input.

**Comment by tomivirkki** [comment]
I guess #56 would also fix this?

**Comment by web-padawan** [comment]
The solution proposed described in #56 is slightly different at the moment:

> to completely hide the input (so that it doesn’t take space) when some item is selected 

So the internal text field still remains, and while it shows the placeholder, we can now focus it from keyboard (not by mouse, due to `pointer-events: none`).
