### ISSUE TITLE
Should blur when closing on outside click

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-dropdown-menu#68]
*From the [comment](https://github.com/vaadin/vaadin-dropdown-menu/issues/54#issuecomment-345261681) by @jouni:*

There seems to be a problem with this when the `[phone]` mode is applied. When I close the overlay, the focused state is still applied, and can’t be removed by tapping outside the element. Can be reproduced with the Chrome device emulator.

Also, **one addition to the specs** (didn’t consider this before):
- When the overlay is closed by clicking outside the overlay (i.e. not selecting an item), the field should be blurred
- If the overlay is closed by selecting an item or by pressing ESC, the field should stay focused

**Comment by jouni** [comment]
I already started re-evaluating the additional spec.

I think it makes sense on touch devices at least, that the field is always blurred when the overlay is closed.

But with mouse I’m not 100% sure. It would be nice to have consistent behavior and work the same regardless of mouse/touch, but the native select element does remain focused when the overlay/dropdown is closed (even when clicking outside).
