### ISSUE TITLE
Readme's Live Demo & API documentation points to 404

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-dropdown-menu#91]
[Live Demo ↗](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-dropdown-menu/demo/)
|
[API documentation ↗](https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-dropdown-menu/)

**Comment by web-padawan** [comment]
Fixed in e903bd8
